# logout
app_login:
  path: /
  controller: App\Controller\AppController::login
login:
  path: /login
  controller: App\Controller\AppController::login
# logout
app_logout:
    path: /logout
    methods: GET

# --- --- --- Administrador --- --- ---

# --- --- END Administrador --- --- ---

# --- --- --- Digitador --- --- ---

# --- --- END Digitador --- --- ---


# controllers:
#     resource: ../src/Controller/
#     type: annotation

# kernel:
#     resource: ../src/Kernel.php
#     type: annotation
